/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
	collections: {
		accounts: Account;
		companies: Company;
		documentation: Documentation;
		transactions: Transaction;
		users: User;
		vehicles: Vehicle;
	};
	globals: {};
}
export interface Account {
	id: string;
	accountName: string;
	accountNumber?: string;
	balance: number;
	startingBalance?: number;
	updatedAt: string;
	createdAt: string;
}
export interface Company {
	id: string;
	companyName: string;
	bankAccount?: string;
	notes?: string;
	contacts?: {
		name?: string;
		phoneNumber?: string;
		discord?: string;
		id?: string;
		blockName?: string;
		blockType: "contact";
	}[];
	updatedAt: string;
	createdAt: string;
}
export interface Documentation {
	id: string;
	title?: string;
	sections?: {
		sectionContent?: {
			[k: string]: unknown;
		}[];
		id?: string;
		blockName?: string;
		blockType: "section";
	}[];
	updatedAt: string;
	createdAt: string;
}
export interface Transaction {
	id: string;
	date: string;
	transactionType: "donation" | "expense" | "revenue";
	revenueType?:
		| "taxi"
		| "limo"
		| "city"
		| "gang"
		| "helicopter"
		| "submarine";
	donationType?: "cashCab" | "general";
	expenseType?:
		| "cashCab"
		| "foodDrink"
		| "gas"
		| "payroll"
		| "repairs"
		| "other";
	expenseOther: string;
	noOfPassenger?: number;
	paymentAmount: number;
	donationAmount: number;
	from:
		| {
				value: string | Account;
				relationTo: "accounts";
		  }
		| {
				value: string | Company;
				relationTo: "companies";
		  }
		| {
				value: string | User;
				relationTo: "users";
		  };
	to:
		| {
				value: string | Account;
				relationTo: "accounts";
		  }
		| {
				value: string | Company;
				relationTo: "companies";
		  }
		| {
				value: string | User;
				relationTo: "users";
		  };
	fromRemaining?: number;
	toRemaining?: number;
	notes?: string;
	vehicle?: {
		value: string | Vehicle;
		relationTo: "vehicles";
	};
	createdBy: {
		value: string | User;
		relationTo: "users";
	};
	updatedBy?: {
		value: string | User;
		relationTo: "users";
	};
	updatedAt: string;
	createdAt: string;
}
export interface User {
	id: string;
	characterName: string;
	title?: string;
	phoneNumber?: string;
	bankAccount?: string;
	discord?: string;
	fiveMID?: string;
	roles?: "admin" | "editor" | "employee" | "user";
	timezone?: string;
	updatedAt: string;
	createdAt: string;
	email: string;
	resetPasswordToken?: string;
	resetPasswordExpiration?: string;
	salt?: string;
	hash?: string;
	loginAttempts?: number;
	lockUntil?: string;
	password?: string;
}
export interface Vehicle {
	id: string;
	vehicle: string;
	licensePlate: string;
	combinedName?: string;
	updatedAt: string;
	createdAt: string;
}
